version: '3.8'

services:
  backend1:
    image: nginx:alpine
    container_name: backend1
    volumes:
      - ./backend1:/usr/share/nginx/html
    networks:
      - lb_network

  backend2:
    image: nginx:alpine
    container_name: backend2
    volumes:
      - ./backend2:/usr/share/nginx/html
    networks:
      - lb_network

  nginx:
    image: nginx:alpine
    container_name: nginx_lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
    networks:
      - lb_network

networks:
  lb_network:
    driver: bridge
